name: CI - Build App

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: cd OpenCore\ Patcher; xcodebuild; cd ..
      - run: cd OpenCore\ Patcher/build/Release; zip -r ../../../OpenCore-Patcher-GUI.app.zip OpenCore\ Patcher.app;
      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenCore-Patcher-GUI.app
          path: OpenCore-Patcher-GUI.app.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OpenCore-Patcher-GUI.app.zip
          tag: ${{ github.ref }}
          file_glob: true
